# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='areas',
            field=models.ManyToManyField(blank=True, to='schools.School'),
        ),
    ]
