# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20171129_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='areas',
        ),
    ]
