# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_remove_county_areas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='County',
            new_name='Area',
        ),
    ]
