# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='none')),
                ('blog_name', models.CharField(max_length=200)),
                ('blog_content', tinymce.models.HTMLField(default='-')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
