# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='none')),
                ('logo', models.ImageField(blank=True, default='avatars/profile.png', null=True, upload_to='avatars')),
                ('school_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone_number', models.CharField(default=0, max_length=15)),
                ('url', models.URLField()),
                ('products', multiselectfield.db.fields.MultiSelectField(choices=[('Motorcycle', 'Motorcycle'), ('Car', 'Car'), ('CarTowing', 'Car Towing'), ('RigidTruck', 'Rigid Truck'), ('ArticulatedTruck', 'Articulated Truck'), ('MiniBus', 'Mini Bus'), ('Coach', 'Coach')], default='Car', max_length=66)),
                ('school_type', models.CharField(choices=[('Independent Driving Instructor', 'Independent Driving Instructor'), ('Driving School', 'Driving School'), ('Insurance Company', 'Insurance Company')], default='Driving School', max_length=30)),
                ('rsa_number', models.CharField(max_length=8)),
                ('Area', multiselectfield.db.fields.MultiSelectField(choices=[('Dublin 1', 'Dublin 1'), ('Dublin 2', 'Dublin 2'), ('Dublin 3', 'Dublin 3'), ('Dublin 4', 'Dublin 4'), ('Dublin 5', 'Dublin 5'), ('Dublin 6', 'Dublin 6'), ('Dublin 7', 'Dublin 7'), ('Dublin 8', 'Dublin 8'), ('Dublin 9', 'Dublin 9'), ('Dublin 10', 'Dublin 10'), ('Dublin 11', 'Dublin 11'), ('Dublin 12', 'Dublin 12'), ('Dublin 13', 'Dublin 13'), ('Dublin 14', 'Dublin 14'), ('Dublin 15', 'Dublin 15'), ('Dublin 16', 'Dublin 16'), ('Dublin 17', 'Dublin 17'), ('Dublin 18', 'Dublin 18'), ('Dublin 20', 'Dublin 20'), ('Dublin 22', 'Dublin 22'), ('Dublin 24', 'Dublin 24')], default='Dublin1', max_length=200)),
                ('Business_des', tinymce.models.HTMLField(default='-')),
                ('Lesson_Price_For_12', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('Lesson_Price_For_1', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('areas', models.ManyToManyField(blank=True, to='areas.Area')),
            ],
        ),
    ]
