# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20171121_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='content',
        ),
        migrations.AddField(
            model_name='school',
            name='Area',
            field=models.CharField(choices=[('D1', 'Dublin1'), ('D2', 'Dublin2'), ('D3', 'Dublin3'), ('D4', 'Dublin4'), ('D5', 'Dublin5'), ('D6', 'Dublin6'), ('D7', 'Dublin7'), ('D8', 'Dublin8'), ('D9', 'Dublin9'), ('D10', 'Dublin10'), ('D11', 'Dublin11'), ('D12', 'Dublin12'), ('D13', 'Dublin13'), ('D14', 'Dublin14'), ('D15', 'Dublin15'), ('D16', 'Dublin16'), ('D17', 'Dublin17'), ('D18', 'Dublin18'), ('D20', 'Dublin20'), ('D22', 'Dublin22'), ('D24', 'Dublin24')], default='Dublin1', max_length=2),
        ),
        migrations.AddField(
            model_name='school',
            name='Lesson_Price_For_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='school',
            name='Lesson_Price_For_12',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='school',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
