# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_areas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='rsa_number',
            new_name='adi_number',
        ),
    ]
