# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20171122_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default='none'),
        ),
    ]
