# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='image',
            new_name='logo',
        ),
    ]
