# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_auto_20171126_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Indp', 'Independent Driving Instructor'), ('DS', 'Driving Schoo'), ('IC', 'Insurance Company')], default='DS', max_length=3),
        ),
    ]
