# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Area',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('D1', 'Dublin 1'), ('D2', 'Dublin 2'), ('D3', 'Dublin 3'), ('D4', 'Dublin 4'), ('D5', 'Dublin 5'), ('D6', 'Dublin 6'), ('D7', 'Dublin 7'), ('D8', 'Dublin 8'), ('D9', 'Dublin 9'), ('D10', 'Dublin 10'), ('D11', 'Dublin 11'), ('D12', 'Dublin 12'), ('D13', 'Dublin 13'), ('D14', 'Dublin 14'), ('D15', 'Dublin 15'), ('D16', 'Dublin 16'), ('D17', 'Dublin 17'), ('D18', 'Dublin 18'), ('D20', 'Dublin 20'), ('D22', 'Dublin 22'), ('D24', 'Dublin 24')], default='Dublin1', max_length=74),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Independent Driving Instructor', 'Independent Driving Instructor'), ('Driving School', 'Driving School'), ('Insurance Company', 'Insurance Company')], default='Driving School', max_length=3),
        ),
    ]
