# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_auto_20171126_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='products',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Motorcycle', 'Motorcycle'), ('Car', 'Car'), ('Bus', 'Bus')], default='Car', max_length=18),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Independent Driving Instructor', 'Independent Driving Instructor'), ('Driving School', 'Driving School'), ('Insurance Company', 'Insurance Company')], default='Driving School', max_length=30),
        ),
    ]
