# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:36
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_auto_20171127_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Area',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Dublin 1', 'Dublin 1'), ('Dublin 2', 'Dublin 2'), ('Dublin 3', 'Dublin 3'), ('Dublin 4', 'Dublin 4'), ('Dublin 5', 'Dublin 5'), ('Dublin 6', 'Dublin 6'), ('Dublin 7', 'Dublin 7'), ('Dublin 8', 'Dublin 8'), ('Dublin 9', 'Dublin 9'), ('Dublin 10', 'Dublin 10'), ('Dublin 11', 'Dublin 11'), ('Dublin 12', 'Dublin 12'), ('Dublin 13', 'Dublin 13'), ('Dublin 14', 'Dublin 14'), ('Dublin 15', 'Dublin 15'), ('Dublin 16', 'Dublin 16'), ('Dublin 17', 'Dublin 17'), ('Dublin 18', 'Dublin 18'), ('Dublin 20', 'Dublin 20'), ('Dublin 22', 'Dublin 22'), ('Dublin 24', 'Dublin 24')], default='Dublin1', max_length=200),
        ),
    ]
