# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_auto_20171127_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Business_des',
            field=models.TextField(default='-'),
        ),
    ]
