# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_remove_county_areas'),
        ('schools', '0015_auto_20171129_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='counties',
            field=models.ManyToManyField(blank=True, to='areas.County'),
        ),
    ]
