# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_school_counties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='counties',
            new_name='areas',
        ),
    ]
